# Generated by Django 5.0.3 on 2024-04-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_brand_active_brand_biography_brand_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('RCD', 'Records'), ('CLT', 'Clothing'), ('PST', 'Posters'), ('MSN', 'Miscellaneous')], default='MSN', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='year',
            field=models.IntegerField(default=2000, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='biography',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
